import re

with open('src/data/sports.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Update SPORTS_CATEGORIES to include all requested categories
new_categories = """export const SPORTS_CATEGORIES = [
  { id: 'all', label: 'All Legends', icon: '🏆' },
  { id: 'football', label: 'Football', icon: '⚽' },
  { id: 'athletics', label: 'Athletics', icon: '🏃' },
  { id: 'atlanta96', label: "Atlanta '96", icon: '🥇' },
  { id: 'boxing', label: 'Boxing', icon: '🥊' },
  { id: 'basketball', label: 'Basketball', icon: '🏀' },
  { id: 'paralympic', label: 'Paralympic Sports', icon: '♿' },
  { id: 'women-sport', label: "Women's Pioneers", icon: '👑' },
  { id: 'modern', label: 'Modern Football Icons', icon: '🌟' },
  { id: 'weightlifting', label: 'Weightlifting & Wrestling', icon: '🏋️' },
  { id: 'racket', label: 'Table Tennis & Tennis', icon: '🏓' },
  { id: 'olympic-history', label: 'Olympic History', icon: '🌍' },
];"""

content = re.sub(
    r'export const SPORTS_CATEGORIES = \[[\s\S]*?\];',
    new_categories,
    content
)

# 2. Add John Obi Mikel (Mikel Obi) and additional legends
# Let's define the new athlete entries
additional_athletes = """
  // --- ATLANTA '96 LEGENDS (ADDITIONAL SQUAD MEMBERS) ---
  {
    id: 'tijani-babangida-sport',
    name: 'Tijani Babangida',
    sport: 'Football',
    category: 'atlanta96',
    primaryEventOrPosition: 'Right Winger ("TJ")',
    era: '1994–2004',
    birthDate: 'September 25, 1973',
    photoUrl: '/images/sports/tijani-babangida.jpg',
    nationality: 'Nigeria 🇳🇬',
    isAtlanta96: true,
    clubAtTime: 'Roda JC / AFC Ajax (Netherlands)',
    olympicRole: 'Gold-medal winning explosive winger; scored vs Japan and assisted in knockout rounds',
    tagline: 'Atlanta \'96 Olympic Gold Medalist & Blistering Super Eagles Winger',
    biography:
      'Tijani Babangida MON, famed throughout world football for his lightning speed and direct wing play, was a crucial weapon in Nigeria\'s 1996 Olympic gold-medal triumph in Atlanta. Born in Kaduna, Babangida scored the vital second goal against Japan in the group stage and repeatedly terrorized opposition fullbacks throughout the tournament. He spent six successful seasons with Dutch powerhouses AFC Ajax, winning the Eredivisie title and KNVB Cup, and represented Nigeria at the 1998 FIFA World Cup in France, scoring a memorable consolation goal against Denmark.',
    achievements: [
      { competition: 'Olympic Games (Atlanta 1996)', year: 1996, medal: 'Gold', event: "Men's Football", description: 'Scored in 2–0 win vs Japan and featured in the famous semifinal and final victories.' },
      { competition: 'Dutch Eredivisie', year: 1998, medal: 'Champion', description: 'Won Dutch league championship with AFC Ajax.' },
      { competition: 'KNVB Cup', year: '1998, 1999', medal: 'Champion', description: 'Two-time Dutch Cup winner with Ajax.' },
      { competition: 'Africa Cup of Nations', year: 2000, medal: 'Silver', description: 'AFCON 2000 runner-up; scored twice in semifinal vs South Africa.' },
    ],
    internationalRecord: ['36 appearances and 5 goals for Nigeria', 'Scored at 1998 FIFA World Cup vs Denmark in Round of 16'],
    nationalTeamRecord: '36 Caps, 5 Goals; Atlanta \'96 Gold Medallist',
    awards: ['Member of the Order of the Niger (MON)'],
    sportingImpact: 'His blistering speed on the right flank defined the classic era of 1990s Nigerian attacking football.',
    whereAreTheyNow: 'President of the National Association of Nigeria Professional Footballers (NANPF) and football administrator.',
    sources: ['IOC Atlanta 1996 Official Football Technical Report', 'AFC Ajax Historical Player Registry'],
  },
  {
    id: 'garba-lawal-sport',
    name: 'Garba Lawal',
    sport: 'Football',
    category: 'atlanta96',
    primaryEventOrPosition: 'Utility Midfielder / Left Midfield',
    era: '1995–2006',
    birthDate: 'May 22, 1974',
    photoUrl: '/images/sports/garba-lawal.jpg',
    nationality: 'Nigeria 🇳🇬',
    isAtlanta96: true,
    clubAtTime: 'Espérance de Tunis (Tunisia)',
    olympicRole: 'Starting utility workhorse in midfield; played key minutes across all tournament matches',
    tagline: 'Atlanta \'96 Olympic Gold Medalist & World Cup Match Winner vs Spain',
    biography:
      'Garba Lawal MON is widely regarded as one of the most dedicated, tactically disciplined, and versatile footballers ever to don the green and white jersey of Nigeria. In Atlanta \'96, Lawal\'s tireless engine, defensive positioning, and tactical awareness provided the essential defensive stability that allowed Okocha, Babangida, and Kanu to flourish. In the 1998 FIFA World Cup in France, Lawal famously scored the equalizing goal against Spain from a seemingly impossible angle that sparked Nigeria\'s historic 3–2 victory over Andoni Zubizarreta and the Spanish.',
    achievements: [
      { competition: 'Olympic Games (Atlanta 1996)', year: 1996, medal: 'Gold', event: "Men's Football", description: 'Pivotal starting midfielder in Nigeria\'s Olympic gold medal triumph.' },
      { competition: 'FIFA World Cup', year: 1998, medal: 'Record', description: 'Scored famous winning angle goal in 3–2 victory over Spain in Nantes.' },
      { competition: 'Africa Cup of Nations', year: '2000, 2002, 2004, 2006', medal: 'Bronze', description: 'Won 1 silver and 3 bronze medals across four consecutive AFCON tournaments.' },
      { competition: 'Bulgarian Cup', year: 2003, medal: 'Champion', description: 'Won Bulgarian Cup with Levski Sofia.' },
    ],
    internationalRecord: ['57 appearances and 6 goals for Nigeria', 'Competed in two FIFA World Cups (1998, 2002) and four AFCONs'],
    nationalTeamRecord: '57 Caps, 6 Goals; Atlanta \'96 Gold Medallist',
    awards: ['Member of the Order of the Niger (MON)'],
    sportingImpact: 'The gold standard of tactical discipline and selfless commitment in Nigerian sports history.',
    whereAreTheyNow: 'Football coach, scout, and executive board member of Kaduna United.',
    sources: ['IOC Atlanta 1996 Football Official Statistics', 'FIFA World Cup 1998 Historical Archive'],
  },

  // --- MODERN NIGERIAN FOOTBALL ICONS (INCLUDING MIKEL OBI) ---
  {
    id: 'mikel-obi-sport',
    name: 'John Obi Mikel (Mikel Obi)',
    sport: 'Football',
    category: 'modern',
    primaryEventOrPosition: 'Defensive Midfielder / Super Eagles Captain',
    era: '2005–2019',
    birthDate: 'April 22, 1987',
    photoUrl: '/images/sports/mikel-obi.jpg',
    nationality: 'Nigeria 🇳🇬',
    isAtlanta96: false,
    tagline: 'AFCON 2013 Champion, 2016 Olympic Bronze Medalist & UEFA Champions League Winner',
    biography:
      'John Michael Nchekwube Obinna, universally revered as John Obi Mikel, is one of the most decorated and respected captains in African sports history. Born in Jos, Plateau State, Mikel announced his generational talent at the 2005 FIFA World Youth Championship in the Netherlands, capturing the Silver Ball behind Lionel Messi. Joining Chelsea FC in 2006, he spent 11 trophy-laden seasons in London, winning the UEFA Champions League (2012), UEFA Europa League (2013), two Premier League titles, three FA Cups, and a League Cup in 372 appearances. On the international stage, Mikel was the indomitable heartbeat of Stephen Keshi\'s 2013 Africa Cup of Nations winning squad in South Africa. In 2016, Mikel displayed unparalleled patriotism by personally funding Nigeria\'s Olympic football squad in Rio when logistical funding failed, captaining the Dream Team VI to an Olympic Bronze medal. He captained Nigeria at the 2014 and 2018 FIFA World Cups, retiring with 91 caps as a national sporting hero.',
    achievements: [
      { competition: 'Africa Cup of Nations', year: 2013, medal: 'Champion', description: 'Midfield maestro of Nigeria\'s 3rd AFCON title in South Africa; named to CAF Team of the Tournament.' },
      { competition: 'Olympic Games (Rio 2016)', year: 2016, medal: 'Bronze', event: "Men's Football", description: 'Captained Nigeria to Olympic Bronze; personally financed squad logistics.' },
      { competition: 'UEFA Champions League', year: 2012, medal: 'Champion', description: 'Played full 120 minutes in midfield as Chelsea defeated Bayern Munich in Munich.' },
      { competition: 'UEFA Europa League', year: 2013, medal: 'Champion', description: 'European champion with Chelsea in Amsterdam.' },
      { competition: 'English Premier League', year: '2009–10, 2014–15', medal: 'Champion', description: 'Two-time Premier League champion with Chelsea.' },
      { competition: 'English FA Cup', year: '2007, 2009, 2012', medal: 'Champion', description: 'Three-time FA Cup winner at Wembley Stadium.' },
      { competition: 'FIFA World Youth Championship', year: 2005, medal: 'Silver', description: 'Silver Ball winner as 2nd best player in tournament behind Lionel Messi.' },
    ],
    internationalRecord: [
      '91 caps and 6 goals for the Super Eagles of Nigeria',
      'AFCON 2013 Champion; Bronze in 2006, 2010, 2019',
      '2016 Rio Olympic Bronze Medalist (Team Captain)',
      'Played in 2014 and 2018 FIFA World Cups',
    ],
    nationalTeamRecord: '91 Caps, 6 Goals; Long-standing Super Eagles Captain & 2016 Olympic Team Captain',
    awards: [
      'CAF Most Promising African Player (2005)',
      'FIFA World Youth Championship Silver Ball (2005)',
      'Chelsea Young Player of the Year (2007, 2008)',
      'African Footballer of the Year Runner-Up (2013)',
      'Officer of the Order of the Niger (OON)',
    ],
    sportingImpact:
      'Celebrated for tactical mastery, calmness in possession, and supreme selflessness—famously stepping up to financially secure Nigeria\'s Olympic campaign in 2016 to deliver Olympic Bronze.',
    whereAreTheyNow: 'Host of the globally acclaimed "The Obi One Podcast"; grassroots sports philanthropist and UEFA ambassador.',
    sources: [
      'CAF AFCON 2013 Official Technical Report',
      'IOC Rio 2016 Olympic Games Football Archive',
      'Chelsea FC Official Historical Registry (372 Appearances)',
      'FIFA U-20 World Championship 2005 Official Records',
    ],
  },
  {
    id: 'victor-moses-sport',
    name: 'Victor Moses',
    sport: 'Football',
    category: 'modern',
    primaryEventOrPosition: 'Winger / Wing-Back',
    era: '2012–2018',
    birthDate: 'December 12, 1990',
    photoUrl: '/images/sports/victor-moses.jpg',
    nationality: 'Nigeria 🇳🇬',
    isAtlanta96: false,
    tagline: 'AFCON 2013 Champion & Premier League Winner with Chelsea',
    biography:
      'Victor Moses is an electric winger who overcame severe childhood tragedy in Kaduna to reach the summit of world football. Representing Nigeria at senior level, Moses was the breakout star of Nigeria\'s AFCON 2013 victory in South Africa, winning the Fair Play Award and scoring crucial goals against Ethiopia. Under Antonio Conte at Chelsea, Moses reinvented himself as a world-class right wing-back, playing 34 Premier League matches to win the 2016–17 title. He scored for Nigeria at the 2018 FIFA World Cup in Russia against Argentina.',
    achievements: [
      { competition: 'Africa Cup of Nations', year: 2013, medal: 'Champion', description: 'Key protagonist in South Africa; named in AFCON Team of the Tournament.' },
      { competition: 'English Premier League', year: 2017, medal: 'Champion', description: 'Transformed into champion right wing-back for Chelsea FC.' },
      { competition: 'UEFA Europa League', year: '2013, 2019', medal: 'Champion', description: 'Two-time Europa League winner with Chelsea.' },
      { competition: 'English FA Cup', year: 2018, medal: 'Champion', description: 'FA Cup winner at Wembley Stadium.' },
    ],
    internationalRecord: ['38 appearances and 12 goals for Nigeria', 'Scored against Argentina at the 2018 FIFA World Cup'],
    nationalTeamRecord: '38 Caps, 12 Goals; 2013 AFCON Champion; 2014 & 2018 World Cup',
    awards: ['AFCON 2013 Samsung Fair Play Player of the Tournament', 'Chelsea Players\' Player of the Year nominee'],
    sportingImpact: 'A symbol of resilience and supreme tactical versatility on the world stage.',
    whereAreTheyNow: 'Active professional footballer (Luton Town FC).',
    sources: ['CAF AFCON 2013 Tournament Report', 'Premier League Official Player Archive'],
  },
  {
    id: 'alex-iwobi-sport',
    name: 'Alex Iwobi',
    sport: 'Football',
    category: 'modern',
    primaryEventOrPosition: 'Central Midfielder / Playmaker',
    era: '2015–Present',
    birthDate: 'May 3, 1996',
    photoUrl: '/images/sports/alex-iwobi.jpg',
    nationality: 'Nigeria 🇳🇬',
    isAtlanta96: false,
    tagline: 'World Cup Qualification Hero & Premier League Playmaking Workhorse',
    biography:
      'Alexander Chuka Iwobi is the nephew of Nigerian football royalty Jay-Jay Okocha. Born in Lagos and raised in London, Iwobi chose to represent Nigeria over England at senior level. In October 2017, Iwobi scored the famous solitary goal in Uyo against Zambia to seal Nigeria\'s qualification for the 2018 FIFA World Cup. He scored for Arsenal in the 2019 UEFA Europa League final and has accumulated over 270 Premier League appearances for Arsenal, Everton, and Fulham, while serving as the creative engine of the Super Eagles in their run to the AFCON 2023 final.',
    achievements: [
      { competition: 'Africa Cup of Nations', year: 2023, medal: 'Silver', description: 'Started every match as Nigeria reached the AFCON final in Abidjan.' },
      { competition: 'English FA Cup', year: 2017, medal: 'Champion', description: 'FA Cup champion with Arsenal.' },
      { competition: 'FIFA World Cup Qualifier', year: 2017, medal: 'Record', description: 'Scored decisive winner against Zambia to send Nigeria to Russia 2018.' },
    ],
    internationalRecord: ['80+ caps and 10 goals for Nigeria', 'Represented Nigeria at 2018 FIFA World Cup and three AFCON tournaments'],
    nationalTeamRecord: '80+ Caps, 10 Goals; AFCON 2019 Bronze, AFCON 2023 Silver',
    awards: ['CAF Youth Player of the Year (2016)', 'Fulham Players\' Key Contributor'],
    sportingImpact: 'Carries on the proud legacy of creative Nigerian midfield football into the modern era.',
    whereAreTheyNow: 'Active Premier League midfield starter for Fulham FC and Nigeria Super Eagles.',
    sources: ['FIFA World Cup Archives', 'Premier League Official Player Stats'],
  },
  {
    id: 'wilfred-ndidi-sport',
    name: 'Wilfred Ndidi',
    sport: 'Football',
    category: 'modern',
    primaryEventOrPosition: 'Defensive Midfielder',
    era: '2015–Present',
    birthDate: 'December 16, 1996',
    photoUrl: '/images/sports/wilfred-ndidi.jpg',
    nationality: 'Nigeria 🇳🇬',
    isAtlanta96: false,
    tagline: 'FA Cup Winner & Europe\'s Premier Tackling and Interception Master',
    biography:
      'Onyinye Wilfred Ndidi is widely recognized as one of the most effective ball-winning defensive midfielders in contemporary world football. Born in Lagos and developed at Nath Boys Academy, Ndidi moved from Genk to Leicester City in 2017. For three consecutive Premier League seasons, Ndidi ranked #1 or #2 across all of European football in total successful tackles and interceptions. He lifted the English FA Cup in 2021 with Leicester City and has earned over 58 caps for the Super Eagles.',
    achievements: [
      { competition: 'English FA Cup', year: 2021, medal: 'Champion', description: 'Won FA Cup with Leicester City against Chelsea at Wembley.' },
      { competition: 'FA Community Shield', year: 2021, medal: 'Champion', description: 'Defeated Manchester City at Wembley.' },
      { competition: 'Premier League Stat Leader', year: '2018, 2019, 2020', medal: 'Record', description: 'Topped Premier League tackle charts with 143+ tackles per season.' },
    ],
    internationalRecord: ['58 caps for Nigeria', 'Represented Nigeria at 2018 FIFA World Cup and AFCON 2019 (Bronze)'],
    nationalTeamRecord: '58 Caps; Key defensive anchor for the Super Eagles',
    awards: ['Leicester City Young Player of the Year (2017, 2018)'],
    sportingImpact: 'Redefined defensive midfield metrics in England while pursuing a degree in business management at De Montfort University.',
    whereAreTheyNow: 'Active midfielder for Leicester City in the Premier League and the Nigeria Super Eagles.',
    sources: ['Premier League Official Stats Archive', 'CAF Super Eagles Registry'],
  },
  {
    id: 'samuel-chukwueze-sport',
    name: 'Samuel Chukwueze',
    sport: 'Football',
    category: 'modern',
    primaryEventOrPosition: 'Right Winger',
    era: '2015–Present',
    birthDate: 'May 22, 1999',
    photoUrl: '/images/sports/samuel-chukwueze.jpg',
    nationality: 'Nigeria 🇳🇬',
    isAtlanta96: false,
    tagline: 'UEFA Europa League Winner & AC Milan Winger',
    biography:
      'Samuel Chimerenka Chukwueze MON is an elusive, rapid right-winger developed at Diamond Football Academy in Umuahia. Chukwueze first dazzled on the international stage at the 2015 FIFA U-17 World Cup in Chile, winning the Bronze Boot. Moving to Villarreal CF in Spain, he won the 2021 UEFA Europa League title against Manchester United and scored iconic goals at the Santiago Bernabéu and Allianz Arena. In 2023, he completed a high-profile move to Italian giants AC Milan.',
    achievements: [
      { competition: 'UEFA Europa League', year: 2021, medal: 'Champion', description: 'Defeated Manchester United in Gdansk with Villarreal CF.' },
      { competition: 'FIFA U-17 World Cup', year: 2015, medal: 'Champion', description: 'World champion in Chile; Bronze Boot winner (3 goals, 3 assists).' },
      { competition: 'Africa Cup of Nations', year: 2023, medal: 'Silver', description: 'AFCON finalist with Nigeria in Ivory Coast.' },
    ],
    internationalRecord: ['38 caps and 5 goals for Nigeria', 'Scored vs South Africa in AFCON 2019 quarter-final'],
    nationalTeamRecord: '38 Caps, 5 Goals; AFCON 2019 Bronze, AFCON 2023 Silver',
    awards: ['LaLiga African MVP (2022–23)', 'Member of the Order of the Niger (MON)'],
    sportingImpact: 'A master of 1v1 dribbling and explosive cut-inside finishes at elite European level.',
    whereAreTheyNow: 'Active winger for AC Milan in Serie A and the Nigeria Super Eagles.',
    sources: ['UEFA Europa League Archives', 'La Liga Official Player Stats'],
  },
  {
    id: 'kelechi-iheanacho-sport',
    name: 'Kelechi Iheanacho',
    sport: 'Football',
    category: 'modern',
    primaryEventOrPosition: 'Forward ("Senior Man Kelz")',
    era: '2013–Present',
    birthDate: 'October 3, 1996',
    photoUrl: '/images/sports/kelechi-iheanacho.jpg',
    nationality: 'Nigeria 🇳🇬',
    isAtlanta96: false,
    tagline: 'FIFA U-17 Golden Ball Winner & FA Cup Champion',
    biography:
      'Kelechi Promise Iheanacho is a clinical forward born in Imo State. At the 2013 FIFA U-17 World Cup in the UAE, Iheanacho produced one of the most dominant youth performances ever seen, scoring 6 goals and providing 7 assists to win the tournament Golden Ball and Silver Boot as Nigeria won the title. He developed at Manchester City, where he recorded the best minutes-per-goal ratio in Premier League history for players with 10+ goals. Moving to Leicester City, he became the highest-scoring African player in FA Cup history and won the 2021 FA Cup.',
    achievements: [
      { competition: 'FIFA U-17 World Cup', year: 2013, medal: 'Champion', description: 'Golden Ball winner as Best Player of the tournament in UAE (6 goals, 7 assists).' },
      { competition: 'English FA Cup', year: 2021, medal: 'Champion', description: 'Scored 4 goals in Leicester City\'s FA Cup winning campaign.' },
      { competition: 'English League Cup', year: 2016, medal: 'Champion', description: 'Won with Manchester City.' },
      { competition: 'FA Cup All-Time Scoring', year: 2023, medal: 'Record', description: 'Most FA Cup goals by an African player (18 goals).' },
    ],
    internationalRecord: ['55 caps and 15 goals for Nigeria', 'Scored winning penalty in AFCON 2023 semifinal shootout vs South Africa'],
    nationalTeamRecord: '55 Caps, 15 Goals; AFCON 2019 Bronze, AFCON 2023 Silver',
    awards: ['FIFA U-17 World Cup Golden Ball (2013)', 'Premier League Player of the Month (March 2021)', 'CAF Most Promising Talent (2013, 2016)'],
    sportingImpact: 'Beloved nationwide for his clutch finishing and vibrant cultural personality.',
    whereAreTheyNow: 'Active striker for Sevilla FC in La Liga and the Nigeria Super Eagles.',
    sources: ['FIFA U-17 World Cup 2013 Technical Report', 'The FA Cup Official Records'],
  },
  {
    id: 'taiwo-awoniyi-sport',
    name: 'Taiwo Awoniyi',
    sport: 'Football',
    category: 'modern',
    primaryEventOrPosition: 'Center Forward',
    era: '2013–Present',
    birthDate: 'August 12, 1997',
    photoUrl: '/images/sports/taiwo-awoniyi.jpg',
    nationality: 'Nigeria 🇳🇬',
    isAtlanta96: false,
    tagline: 'FIFA U-17 World Champion & Premier League Record Breaker',
    biography:
      'Taiwo Micheal Awoniyi is a powerhouse center forward born in Ilorin, Kwara State. He announced himself at the 2013 FIFA U-17 World Cup in the UAE, scoring 4 goals to help Nigeria capture the trophy. After productive stints in the German Bundesliga with Union Berlin (where he scored 20 goals in a single season), Awoniyi joined Nottingham Forest in the English Premier League, where he became the first Forest player in 28 years to score in seven consecutive Premier League matches.',
    achievements: [
      { competition: 'FIFA U-17 World Cup', year: 2013, medal: 'Champion', description: 'World champion in UAE; scored 4 tournament goals.' },
      { competition: 'English Premier League Record', year: 2023, medal: 'Record', description: 'Scored in 7 consecutive Premier League appearances for Nottingham Forest.' },
      { competition: 'German Bundesliga', year: 2022, medal: 'Record', description: 'Scored 15 Bundesliga goals for Union Berlin to qualify them for Europe.' },
    ],
    internationalRecord: ['8 caps and 2 goals for Nigeria', 'Scored vs Sudan at AFCON 2021'],
    nationalTeamRecord: '8 Caps, 2 Goals; Super Eagles Striker',
    awards: ['Nottingham Forest Player of the Month'],
    sportingImpact: 'A powerful target man embodying humility, determination, and community development in Kwara State.',
    whereAreTheyNow: 'Active Premier League striker for Nottingham Forest and Nigeria Super Eagles.',
    sources: ['Premier League Official Records', 'FIFA U-17 World Cup Archive'],
  },

  // --- ADDITIONAL WOMEN'S FOOTBALL PIONEERS ---
  {
    id: 'mercy-akide-sport',
    name: 'Mercy Akide-Udoh',
    sport: 'Football',
    category: 'women-sport',
    primaryEventOrPosition: 'Striker / Forward',
    era: '1990–2004',
    birthDate: 'August 26, 1975',
    photoUrl: '/images/sports/mercy-akide.jpg',
    nationality: 'Nigeria 🇳🇬',
    tagline: 'Inaugural African Women\'s Footballer of the Year & Super Falcons Legend',
    biography:
      'Mercy Akide-Udoh is the trailblazing pioneer of African women\'s football. Born in Port Harcourt, Rivers State, Akide made history in 2001 by becoming the first-ever recipient of the CAF African Women\'s Footballer of the Year award. She represented Nigeria in three FIFA Women\'s World Cups (1995, 1999, 2003) and two Olympic Games (Sydney 2000, Athens 2004). At the 1999 World Cup in the United States, Akide was named to the FIFA All-Star Team as Nigeria reached the quarterfinals, scoring in famous victories over North Korea and Denmark.',
    achievements: [
      { competition: 'African Women\'s Footballer of the Year', year: 2001, medal: 'Honour', description: 'Inaugural winner of CAF\'s Women\'s Footballer of the Year award.' },
      { competition: 'Women\'s Africa Cup of Nations', year: '1998, 2000, 2002', medal: 'Champion', description: 'Three-time African champion with the Super Falcons; top scorer in 1998 and 2000.' },
      { competition: 'FIFA Women\'s World Cup Quarterfinal', year: 1999, medal: 'Record', description: 'Named to FIFA World Cup All-Star Team.' },
    ],
    internationalRecord: ['Over 30 international goals for Nigeria', 'Played in three World Cups and two Olympic Games'],
    nationalTeamRecord: 'Pioneering Super Falcons Striker; 3x WAFCON Champion',
    awards: ['First CAF African Women\'s Footballer of the Year (2001)', 'FIFA All-Star Selection (1999, 2004)'],
    sportingImpact: 'Paved the path for generations of African women footballers to play professionally in Europe and the United States.',
    whereAreTheyNow: 'Elite youth football coach and FIFA technical ambassador based in Virginia, USA.',
    sources: ['FIFA Women\'s World Cup 1999 Official Technical Report', 'CAF Historical Registry'],
  },
  {
    id: 'florence-omagbemi-sport',
    name: 'Florence Omagbemi',
    sport: 'Football',
    category: 'women-sport',
    primaryEventOrPosition: 'Central Midfielder / Legendary Captain',
    era: '1991–2004',
    birthDate: 'February 2, 1975',
    photoUrl: '/images/sports/florence-omagbemi.jpg',
    nationality: 'Nigeria 🇳🇬',
    tagline: 'Historic Super Falcons Captain & WAFCON Winner as Player and Coach',
    biography:
      'Florence Omagbemi is one of the most authoritative and iconic captains in the history of African sport. Born in Warri, Delta State, Omagbemi captained the Super Falcons for over a decade, leading them to four consecutive Women\'s Africa Cup of Nations championships (1998, 2000, 2002, 2004). She captained Nigeria at four FIFA Women\'s World Cups (1991, 1995, 1999, 2003) and the 2000 Sydney Olympics. In 2016, she made history by coaching the Super Falcons to the WAFCON title in Cameroon—becoming the first woman ever to win the championship as both player and coach.',
    achievements: [
      { competition: 'Women\'s Africa Cup of Nations (Player)', year: '1998, 2000, 2002, 2004', medal: 'Champion', description: 'Captained Super Falcons to four consecutive African titles.' },
      { competition: 'Women\'s Africa Cup of Nations (Coach)', year: 2016, medal: 'Champion', description: 'First woman in African football history to win WAFCON as both player and coach.' },
      { competition: 'FIFA Women\'s World Cup', year: '1991, 1995, 1999, 2003', medal: 'Record', description: 'Captained Nigeria across four consecutive World Cups.' },
    ],
    internationalRecord: ['Captained Nigeria in over 80 matches across 14 years', 'Four World Cups and Sydney 2000 Olympics'],
    nationalTeamRecord: 'Iconic Super Falcons Captain; 4x WAFCON Champion as Player, 1x as Coach',
    awards: ['CAF Women\'s Coach of the Year Nominee (2016)'],
    sportingImpact: 'A towering matriarch of African sports leadership who proved female tactical mastery at national team level.',
    whereAreTheyNow: 'FIFA and CAF technical development instructor and international football consultant.',
    sources: ['FIFA Women\'s Football Leadership Archive', 'CAF Technical Study Group 2016'],
  },
  {
    id: 'onome-ebi-sport',
    name: 'Onome Ebi',
    sport: 'Football',
    category: 'women-sport',
    primaryEventOrPosition: 'Central Defender',
    era: '2003–Present',
    birthDate: 'May 8, 1983',
    photoUrl: '/images/sports/onome-ebi.jpg',
    nationality: 'Nigeria 🇳🇬',
    tagline: 'Record 6 FIFA Women\'s World Cup Tournaments & 4x WAFCON Champion',
    biography:
      'Onome Ebi is a living legend of world football endurance. Born in Lagos, Ebi made history at the 2023 FIFA Women\'s World Cup in Australia and New Zealand by becoming the first African footballer (male or female) to compete in six FIFA World Cups (2003, 2007, 2011, 2015, 2019, 2023). A bedrock of defensive steel for over two decades, she has won four Women\'s Africa Cup of Nations titles with the Super Falcons (2010, 2014, 2016, 2018).',
    achievements: [
      { competition: 'FIFA Women\'s World Cup Record', year: '2003, 2007, 2011, 2015, 2019, 2023', medal: 'Record', description: 'First African footballer in history to play in six FIFA World Cup tournaments.' },
      { competition: 'Women\'s Africa Cup of Nations', year: '2010, 2014, 2016, 2018', medal: 'Champion', description: 'Four-time African champion with the Super Falcons.' },
      { competition: 'Chinese Women\'s League', year: 2018, medal: 'Champion', description: 'Won Chinese League title with Henan Jianye.' },
    ],
    internationalRecord: ['Over 100 caps for the Super Eagles / Super Falcons', 'Six FIFA World Cup appearances spanning 20 years'],
    nationalTeamRecord: 'Over 100 Caps; 4x WAFCON Champion; 6x World Cup Player',
    awards: ['NFF Player of the Year', 'CAF Legend Award'],
    sportingImpact: 'Her 20-year international longevity shattered all African athletic endurance records.',
    whereAreTheyNow: 'Active veteran player (Naija Ratels) and youth football mentor.',
    sources: ['FIFA Women\'s World Cup Official Records', 'CAF Super Falcons Archives'],
  },
  {
    id: 'desire-oparanozie-sport',
    name: 'Desire Oparanozie',
    sport: 'Football',
    category: 'women-sport',
    primaryEventOrPosition: 'Striker / Forward',
    era: '2010–2023',
    birthDate: 'December 17, 1993',
    photoUrl: '/images/sports/desire-oparanozie.jpg',
    nationality: 'Nigeria 🇳🇬',
    tagline: '4x WAFCON Champion & Two-Time Tournament Final Match-Winner',
    biography:
      'Ugochi Desire Oparanozie is one of the most clutch and physically dominant strikers in Nigerian football history. Born in Owerri, Imo State, Oparanozie was the ultimate big-game player, scoring the only and decisive goal in the 2014 WAFCON final against Cameroon in Windhoek, and repeating the heroics by scoring the 84th-minute winner against Cameroon before 40,000 hostile fans in Yaoundé in the 2016 final. She won four WAFCON titles (2010, 2014, 2016, 2018), captained the Super Falcons at the 2019 World Cup, and spent six prolific seasons in France with Guingamp.',
    achievements: [
      { competition: 'Women\'s Africa Cup of Nations', year: '2010, 2014, 2016, 2018', medal: 'Champion', description: 'Four-time African champion; Golden Boot winner in 2014.' },
      { competition: 'WAFCON Final Match-Winner', year: '2014, 2016', medal: 'Record', description: 'Only player in history to score the solitary winning goal in two separate WAFCON finals.' },
      { competition: 'FIFA Women\'s World Cup', year: '2011, 2015, 2019, 2023', medal: 'Record', description: 'Competed across four FIFA World Cups; captained squad in 2019.' },
    ],
    internationalRecord: ['35 international goals for Nigeria', 'Competed in four FIFA Women\'s World Cups'],
    nationalTeamRecord: 'Over 60 Caps, 35 Goals; 4x WAFCON Champion',
    awards: ['WAFCON Golden Boot (2014)', 'Guingamp Player of the Season'],
    sportingImpact: 'Fearless advocate for gender equality and equal allowances for female footballers in Nigeria.',
    whereAreTheyNow: 'Retired from active football following the 2023 World Cup; women\'s sports advocate and commentator.',
    sources: ['CAF Women\'s Africa Cup of Nations Archives', 'FIFA Women\'s World Cup Records'],
  },

  // --- ADDITIONAL ATHLETICS HEROES ---
  {
    id: 'blessing-okagbare-sport',
    name: 'Blessing Okagbare',
    sport: 'Athletics',
    category: 'athletics',
    primaryEventOrPosition: 'Long Jump & 100m / 200m Sprints',
    era: '2007–2021',
    birthDate: 'October 9, 1988',
    photoUrl: '/images/sports/blessing-okagbare.jpg',
    nationality: 'Nigeria 🇳🇬',
    tagline: 'Olympic Silver Medalist & Commonwealth Games Double Sprint Champion',
    biography:
      'Blessing Okagbare is one of the most naturally gifted multi-event track and field athletes in African history. Born in Sapele, Delta State, Okagbare won the Olympic silver medal in the long jump at the 2008 Beijing Olympics at just 19 years old (leaping 6.91m). At the 2013 World Athletics Championships in Moscow, she became the first African athlete to medal in both a sprint and a jump at the same World Championships (silver in long jump with 6.99m, bronze in 200m with 22.32s). At the 2014 Commonwealth Games in Glasgow, she captured double sprint gold in the 100m and 200m.',
    achievements: [
      { competition: 'Olympic Games (Beijing 2008)', year: 2008, medal: 'Silver', event: "Women's Long Jump", description: 'Olympic silver medalist with a leap of 6.91m in Beijing.' },
      { competition: 'World Athletics Championships (Moscow 2013)', year: 2013, medal: 'Silver', event: "Long Jump & 200m", description: 'Silver in long jump (6.99m) and Bronze in 200m (22.32s).' },
      { competition: 'Commonwealth Games (Glasgow 2014)', year: 2014, medal: 'Gold', event: "100m & 200m", description: 'Double sprint gold medalist; broke Commonwealth 100m record with 10.85s.' },
      { competition: 'African Championships', year: '2010, 2014', medal: 'Gold', event: "Sprints & Long Jump", description: 'Multiple African gold medalist.' },
    ],
    internationalRecord: ['Personal Bests: 100m - 10.79s; 200m - 22.04s; Long Jump - 7.00m', 'Olympic and World Championship double medalist'],
    nationalTeamRecord: 'Olympic Silver Medallist; Multiple World Championship Medallist',
    awards: ['Guinness World Record for most Diamond League appearances (67)'],
    sportingImpact: 'Dominated African sprint and horizontal jump events for over a decade.',
    whereAreTheyNow: 'Retired track and field athlete and sports mentor.',
    sources: ['World Athletics Official Athlete Profile', 'IOC Beijing 2008 Official Track and Field Results'],
  },
  {
    id: 'divine-oduduru-sport',
    name: 'Divine Oduduru',
    sport: 'Athletics',
    category: 'athletics',
    primaryEventOrPosition: '100m & 200m Sprints ("I Never Expect Am")',
    era: '2014–Present',
    birthDate: 'October 7, 1996',
    photoUrl: '/images/sports/divine-oduduru.jpg',
    nationality: 'Nigeria 🇳🇬',
    tagline: 'Sub-10s & Sub-20s Collegiate Record Breaker & African Champion',
    biography:
      'Ejowvokoghene Divine Oduduru is a charismatic sprint prodigy born in Ughelli, Delta State. He captured global internet fame in 2016 with his viral "I never expect am" post-race interview. At Texas Tech University in 2019, Oduduru accomplished the rare collegiate sprint double, clocking 9.86s in the 100m and 19.73s in the 200m on the same day—making him the second-fastest African 200m sprinter in history. He won the 200m gold at the 2019 African Games in Rabat.',
    achievements: [
      { competition: 'NCAA Division I Championships', year: 2019, medal: 'Gold', event: "100m & 200m", description: 'Blazed 9.86s (100m) and 19.73s (200m) to win double collegiate national titles.' },
      { competition: 'African Games (Rabat 2019)', year: 2019, medal: 'Gold', event: "200m", description: 'Gold medalist in the men\'s 200m.' },
      { competition: 'World Junior Championships (Eugene 2014)', year: 2014, medal: 'Silver', event: "200m", description: 'Silver medalist with 20.25s.' },
    ],
    internationalRecord: ['Personal Bests: 100m - 9.86s; 200m - 19.73s (One of Africa\'s fastest in history)'],
    nationalTeamRecord: 'Sub-10s 100m sprinter; African Games 200m Champion',
    awards: ['The Bowerman Award Finalist (2019)'],
    sportingImpact: 'Brought youthful vibrance, national pride, and world-class sprint times to Nigerian athletics.',
    whereAreTheyNow: 'Professional track athlete.',
    sources: ['World Athletics Official Records', 'NCAA Track and Field Archives 2019'],
  },
  {
    id: 'francis-obikwelu-sport',
    name: 'Francis Obikwelu',
    sport: 'Athletics',
    category: 'athletics',
    primaryEventOrPosition: '100m & 200m Sprints',
    era: '1994–2008',
    birthDate: 'November 22, 1978',
    photoUrl: '/images/sports/francis-obikwelu.jpg',
    nationality: 'Nigeria 🇳🇬 / Portugal 🇵🇹',
    tagline: 'Olympic Silver Medalist & World Junior Double Champion for Nigeria',
    biography:
      'Francis Obiorah Obikwelu is one of the most explosive sprinters in track and field history. Born in Onitsha, Anambra State, Obikwelu won double gold for Nigeria at the 1996 World Junior Championships in Sydney (100m in 10.21s and 200m in 20.47s), and won bronze for Nigeria in the 200m at the 1999 World Athletics Championships in Seville (setting an African record of 19.84s). After naturalizing to Portugal due to medical neglect following an injury at the Sydney 2000 Olympics while representing Nigeria, Obikwelu won the Olympic silver medal in the 100m at Athens 2004 in 9.86s, setting a European record that stood for nearly two decades.',
    achievements: [
      { competition: 'Olympic Games (Athens 2004)', year: 2004, medal: 'Silver', event: "Men's 100m", description: 'Olympic silver medalist in 9.86s, setting European and former African area records.' },
      { competition: 'World Athletics Championships (Seville 1999)', year: 1999, medal: 'Bronze', event: "Men's 200m (Representing Nigeria)", description: 'Won bronze for Nigeria, clocking 19.84s in the semifinal.' },
      { competition: 'World Junior Championships (Sydney 1996)', year: 1996, medal: 'Gold', event: "100m & 200m (Representing Nigeria)", description: 'Historic double sprint gold for Nigeria.' },
      { competition: 'European Championships (Gothenburg 2006)', year: 2006, medal: 'Gold', event: "100m & 200m", description: 'Double sprint European champion.' },
    ],
    internationalRecord: ['Personal Bests: 100m - 9.86s; 200m - 19.84s', 'Olympic 100m Silver Medalist'],
    nationalTeamRecord: 'World Junior Double Champion for Nigeria; Seville 1999 World Bronze for Nigeria',
    awards: ['European Athlete of the Year (2006)'],
    sportingImpact: 'His career sparked critical national reforms in Nigerian sports medicine and athlete welfare.',
    whereAreTheyNow: 'Sprint coach and international athletics ambassador.',
    sources: ['World Athletics Official Records', 'IOC Athens 2004 Track and Field Results'],
  },

  // --- ADDITIONAL BASKETBALL LEGENDS ---
  {
    id: 'josh-okogie-sport',
    name: 'Josh Okogie',
    sport: 'Basketball',
    category: 'basketball',
    primaryEventOrPosition: 'Shooting Guard / Small Forward (D\'Tigers)',
    era: '2018–Present',
    birthDate: 'September 1, 1998',
    photoUrl: '/images/sports/josh-okogie.jpg',
    nationality: 'Nigeria 🇳🇬',
    tagline: 'NBA Defensive Stopper & D\'Tigers Olympic Leader',
    biography:
      'Joshua Aloiye Okogie is an elite NBA defensive guard and core leader of the Nigerian men\'s national basketball team (D\'Tigers). Born in Lagos, Okogie was selected 20th overall in the 2018 NBA Draft. At the 2019 FIBA Basketball World Cup in China, Okogie starred for D\'Tigers, leading them to direct qualification for the Tokyo 2020 Olympics as Africa\'s highest-ranked nation. In July 2021 in Las Vegas, Okogie helped orchestrate Nigeria\'s historic 90–87 exhibition upset over Team USA—the first time an African nation ever defeated the United States in men\'s basketball.',
    achievements: [
      { competition: 'Exhibition vs Team USA', year: 2021, medal: 'Record', description: 'Helped D\'Tigers defeat USA Basketball 90–87 in Las Vegas; first African victory over USA in history.' },
      { competition: 'FIBA Basketball World Cup', year: 2019, medal: 'Record', description: 'Qualified Nigeria directly to Tokyo 2020 Olympics as Africa\'s top team.' },
      { competition: 'NBA Draft', year: 2018, medal: 'Honour', description: 'Selected in the 1st round (20th overall).' },
    ],
    internationalRecord: ['Core leader of Nigeria D\'Tigers at FIBA World Cup and Tokyo Olympics', 'Over 370 NBA regular-season games played'],
    nationalTeamRecord: 'D\'Tigers Olympic Starter; 2019 World Cup Top Scorer for Nigeria',
    awards: ['NBA Rising Stars Challenge (2019)'],
    sportingImpact: 'A relentless perimeter defender who proudly represents Nigeria across the NBA and global tournaments.',
    whereAreTheyNow: 'Active NBA player for the Phoenix Suns / Charlotte Hornets and Nigeria D\'Tigers.',
    sources: ['NBA Official Player Statistics', 'FIBA World Cup 2019 Official Records'],
  },
  {
    id: 'al-farouq-aminu-sport',
    name: 'Al-Farouq Aminu',
    sport: 'Basketball',
    category: 'basketball',
    primaryEventOrPosition: 'Forward ("The Chief" / D\'Tigers Captain)',
    era: '2010–2022',
    birthDate: 'September 21, 1990',
    photoUrl: '/images/sports/al-farouq-aminu.jpg',
    nationality: 'Nigeria 🇳🇬',
    tagline: 'AfroBasket 2015 Champion & 2x Olympian for Nigeria',
    biography:
      'Al-Farouq Ajadi Aminu, affectionately known as "The Chief" due to his descent from Nigerian royalty, is a towering pillar of Nigerian basketball. Drafted 8th overall in the 2010 NBA Draft, Aminu spent 12 distinguished seasons in the NBA, playing over 700 games. In 2015 in Radès, Tunisia, Aminu captained D\'Tigers to their first-ever FIBA AfroBasket championship, defeating Angola 74–65 in the final to seal qualification for the 2016 Rio Olympics. He represented Nigeria at two Olympic Games (London 2012, Rio 2016).',
    achievements: [
      { competition: 'FIBA AfroBasket Championship', year: 2015, medal: 'Champion', description: 'Captained Nigeria to its first-ever African continental basketball championship in Tunisia.' },
      { competition: 'Olympic Games (London 2012, Rio 2016)', year: '2012, 2016', medal: 'Honour', description: 'Two-time Olympic competitor representing Nigeria.' },
      { competition: 'NBA Career', year: '2010–2022', medal: 'Record', description: 'Played 711 regular-season NBA games across 12 seasons.' },
    ],
    internationalRecord: ['711 NBA regular-season games; 2x Olympian for Nigeria', 'AfroBasket 2015 All-Star Five selection'],
    nationalTeamRecord: 'AfroBasket 2015 Champion & All-Star; 2x Olympian for Nigeria',
    awards: ['AfroBasket 2015 All-Star Five', 'NBA 8th Overall Pick (2010)'],
    sportingImpact: 'With his brother Alade, founded the Aminu Good Works Foundation to build basketball courts and schools across Nigeria.',
    whereAreTheyNow: 'NBA veteran, philanthropist, and founder of youth sports initiatives across southwestern Nigeria.',
    sources: ['FIBA AfroBasket 2015 Tournament Archive', 'NBA Official Historical Player Registry'],
  },
"""

# Insert additional_athletes right before `lucy-ejike-sport`
target_marker = "  // --- PARALYMPIC CHAMPIONS ---"
if target_marker in content:
    content = content.replace(target_marker, additional_athletes + "\n" + target_marker)
else:
    # fallback insert before end of array
    content = content.replace("];\n\n// 4. VERIFIED NATIONAL MEDAL WALL TOTALS", additional_athletes + "\n];\n\n// 4. VERIFIED NATIONAL MEDAL WALL TOTALS")

with open('src/data/sports.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("Updated src/data/sports.ts successfully!")
